# Generated by Django 5.1.2 on 2024-10-17 13:27

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('precios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Producto_Hist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('marca', models.CharField(max_length=255)),
                ('precio_anterior', models.DecimalField(decimal_places=2, max_digits=10)),
                ('precio_actual', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_captura', models.DateTimeField(default=django.utils.timezone.now)),
                ('fecha_aumento', models.DateTimeField(blank=True, null=True)),
                ('cantidad', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('unidad_medida', models.CharField(blank=True, max_length=50, null=True)),
                ('categoria', models.CharField(blank=True, max_length=255, null=True)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='precios.producto')),
                ('supermercado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='precios.supermercado')),
            ],
        ),
    ]
