# Generated by Django 5.1.2 on 2024-10-18 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('precios', '0002_producto_hist'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producto',
            old_name='fecha_fin',
            new_name='fecha_aumento',
        ),
        migrations.AlterField(
            model_name='producto',
            name='id_origen',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='marca',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='producto_hist',
            name='marca',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='producto_hist',
            name='precio_anterior',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
