# Generated by Django 5.1.2 on 2024-10-20 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('precios', '0003_rename_fecha_fin_producto_fecha_aumento_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
