# Generated by Django 5.1.2 on 2024-10-21 20:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('precios', '0004_producto_is_active'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producto_hist',
            old_name='fecha_aumento',
            new_name='fecha_variacion',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='fecha_aumento',
        ),
    ]
